$token = "eyJraWQiOiJBQzkwNVBWczhuTmJ0dXJ5aExjWGxRYmtERWZ2SEpFa3Jsdmg0bUlON05ZPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI1MTIzMGQ5YS1lMDgxLTcwMDgtZmU2Mi1mYmJiMjYwNTFmNjciLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGgtMS5hbWF6b25hd3MuY29tXC9hcC1zb3V0aC0xX2NmQTlkejE1aCIsImNvZ25pdG86dXNlcm5hbWUiOiJ0ZXN0dXNlciIsIm9yaWdpbl9qdGkiOiIzY2Y2ZjRlYS04Yjk2LTQ2ZjUtYjc3YS1lMGEzZjZmY2E1NTYiLCJhdWQiOiI0OW43YWtwOWx1Ymx2cGEwNGRidDJxam9hMiIsImV2ZW50X2lkIjoiZTYyOWJlNjYtMWExNy00NzJkLTliODAtMzQyMjRjMzkzMzYyIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE3Njk4ODM1NDEsImV4cCI6MTc2OTg4NzE0MSwiaWF0IjoxNzY5ODgzNTQxLCJqdGkiOiI0MmZmMmRmMS00ZWNmLTRjMWMtOWRiYy1mZjUzZTlhYTk3ZjYiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20ifQ.VwfNLNUtsuXSEfQ_KEqbCEvKY0Z4g0p6hKkX394_TJT9fqTzH2kAq6--Q5UnxWPdtwhSgfZZaXVrmRiiNGM6TY8ZnPxEIFywWuNV2VVYch4hFWNcYKUO_Eb33ooKaFOs9aVN1EGUr7RRC0sa4e2ajrBx8rVQQK34mbyZsnYWiRS5qTUDbFj6bCDKHckLlLCkVPPaecIByWtLHbG21CQDiSJxszu-RwT_EGHnNqTtlK_z1UrtV1DiDqPvQCtqwAZ6NMP1JZbZUlpvsJGr8hKT1mXe7PELG_Z_Dr8VEoBefaj0Y6uRdt3aO_KIIqn3s2LnezhpHLcl3imTuqn0KAPpVg"

$headers = @{
    "Authorization" = $token
    "Content-Type" = "application/json"
}

$body = @{
    content = "Python is a high-level programming language created by Guido van Rossum. It emphasizes code readability and uses significant indentation. Python supports multiple programming paradigms including procedural, object-oriented, and functional programming."
    question_count = 3
} | ConvertTo-Json

Write-Host "`n🚀 AI LEARNING ASSISTANT - LIVE DEMO" -ForegroundColor Cyan
Write-Host "=" * 50 -ForegroundColor Gray
Write-Host "`n📝 Generating Quiz from Content..." -ForegroundColor Yellow
Write-Host "Topic: Python Programming Basics`n" -ForegroundColor Gray

try {
    $response = Invoke-RestMethod -Uri "https://qtyf9c08b4.execute-api.ap-south-1.amazonaws.com/dev/quiz/generate" -Method Post -Headers $headers -Body $body -TimeoutSec 60
    
    Write-Host "✅ SUCCESS! Quiz Generated by AI`n" -ForegroundColor Green
    Write-Host "=" * 50 -ForegroundColor Gray
    Write-Host "`nQuiz Details:" -ForegroundColor Cyan
    Write-Host "  Title: $($response.title)" -ForegroundColor White
    Write-Host "  Questions: $($response.questions.Count)" -ForegroundColor White
    Write-Host "  Time Limit: $($response.time_limit) seconds" -ForegroundColor White
    Write-Host "  Passing Score: $($response.passing_score)%`n" -ForegroundColor White
    
    Write-Host "Questions:" -ForegroundColor Cyan
    $i = 1
    foreach ($q in $response.questions) {
        Write-Host "`n  Q$i. $($q.text)" -ForegroundColor Yellow
        Write-Host "      Type: $($q.type)" -ForegroundColor Gray
        if ($q.options) {
            foreach ($opt in $q.options) {
                Write-Host "      - $opt" -ForegroundColor White
            }
        }
        $i++
    }
    
    Write-Host "`n" -ForegroundColor Gray
    Write-Host "=" * 50 -ForegroundColor Gray
    Write-Host "✨ AI Learning Assistant is FULLY OPERATIONAL! ✨" -ForegroundColor Green
    Write-Host "=" * 50 -ForegroundColor Gray
    
} catch {
    Write-Host "❌ Error: $($_.Exception.Message)" -ForegroundColor Red
    if ($_.ErrorDetails.Message) {
        Write-Host "Details: $($_.ErrorDetails.Message)" -ForegroundColor Yellow
    }
}
